# Content configuration version
version: 2

# Personal info
name: Bradley Kars
title: System Support Specialist
email: bradley.kars@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: 
github_username:  Bradley-Kars
# stackoverflow_username: 
linkedin_username: bradley-kars
# youtube_username: 

# Additional icon links
additional_links:
#- title: 
#  icon: 
#  url: 
# - title: 
#   icon: 
#   url: 

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Bradley and I’ve done everything from helping to build a budding national organization run by students in the hopes of furthering their education; to running the IT department of a commercial construction company. I’ve now returned to furthering my education where I’m a Dean’s list student at Purdue University Global. Where I’m toward my Bachelor of Science in Cybersecurity with a focus in Game Development, while simultaneously employed as a System Support Specialist Intern.

  I am most skilled in: <mark>System Support</mark> and <mark>Hardware Diagnostics</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CentralSquare Technologies
        link: https://www.centralsquare.com/
        link_text: CentralSquare
        sub_title: System Support Specialist Intern
        caption: March 2022 - Present
        quote: >
          Creating the broadest, smartest and most agile software platform for building safer, smarter communities.
        description: | # this will include new lines to allow paragraphs
            Every company needs its systems properly supported and CentralSquare is no exception. Devloping, deploying, and maintianing software is hard and I play my part making sure the whole company stays connected. I work hand and hand with people from every department to keep their systems functioning as they need.
      - layout: left
        title: Kars Customs
        link: 
        link_text: 
        sub_title: Owner/Lead Repair Tech
        caption: September 2016 - Present
        quote: >
          Aiming to make your life easier by providing support and a knowledge base for your technological needs.
        description: | # this will include new lines to allow paragraphs
            Here to help every step of the way from guiding customers through purchases, to finding them the best deals while supporting their devices for as long as they want to keep them. All under the goal of making it so technology can do its job and truly make their lives easier.
      - layout: left
        title: MarketSource Inc.
        link: https://www.marketsource.com/
        link_text: MarketSource
        sub_title: Team Lead
        caption: July 2018 - March 2020
        quote: >
          Technologists committed to making Target America's easiest, safest, and most joyful place to shop and work.
        description: | # this will include new lines to allow paragraphs
            There to help target customers make informed purchases regarding cellular devices while also offering help maintaining said devices. Our goal is to make sure the customer gets what they need from their devices on plans that just work. This includes but is not limited to helping customers choose their devices, diagnosing and fixing basic device issues, and even communicating with their individual carriers on their behalf.
      - layout: left
        title: ESCO Services LLC
        link: 
        link_text: 
        sub_title: Estimating Engineer - IT Specialist
        caption: January 2012 - May 2015
        quote: >
          Leaders in quality construction and innovation.
        description: | # this will include new lines to allow paragraphs
            Every company needs IT from multimillion dollar organizations to small ma and pa shops and the construction industry is no different. While the systems involved may be less complex devices still need to be maintained, computers kept running, and software configured.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Purdue University Global
        caption: March 2022 - Present
        sub_title: Bachelor of Science in Cybersecurity - Game Development
        quote: >
          With a history of pioneering online education, Purdue Global’s mission is simple: deliver a fully personalized online learning experience that's tailored to the unique needs of working adults—one that gives them the support they need to achieve their goals and creates new opportunities for their future. While maintaining its image as part of the Renowned Purdue University System.
        description: | # this will include new lines to allow paragraphs
          Throughout the process of obtaining my Bachelors in Cybersecurity, with a focus in Game Development, I maintained a 3.98 GPA placing me on the Dean's list. While also using the tools I gained from my Associates degree to begin my work in field as a System Support Specialist Intern.
      - layout: left
        caption: October 2020 – January 2022
        sub_title: Associate of Applied Science in Information Technology - IT Generalist
        description: | # this will include new lines to allow paragraphs
          While pursuing my Associates degree I maintained a 4.00 GPA placing me on the Chancellor’s list while simultaneously obtaining the necessary tools to support an IT infrastructure.

  - title: Coding Classes # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: IT244 - Python Programming
        link: https://github.com/Bradley-Kars/slayerbrk.github.io/tree/main/IT244%20-%20Python%20Programming
        link_text: Python Programming
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A project taken on to further my understanding of coding while gaining my footing in a new programing language.
        description: | # this will include new lines to allow paragraphs
          The start in a long journey to fully understand <mark>Python</mark> a language I'm quickly growing to love. This is the first time I've felt as if coding just make sense and thus holds the highest mantel in my current portfolio.
      - layout: top-middle
        title: IT213 - Software Development Concepts
        link: https://github.com/slayerbrk/slayerbrk.github.io/tree/main/IT213%20-%20%20Software%20Development%20Concepts
        link_text: Software Development Concepts
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Dipping my toes into the world of coding as this is my first ever experience with a fully-fledged programming language.
        description: | # this will include new lines to allow paragraphs
          This project was taken up in the hopes of gaining a better understanding of <mark>C#</mark> though it will be the first of many. This program has helped expand my knowledge earning it a place in my portfolio.
      - layout: top-middle
        title: IT117 - Website Development
        link: https://github.com/slayerbrk/slayerbrk.github.io/tree/main/IT117%20-%20Website%20Development
        link_text: Website Development
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The first website I ever created; it may not be perfect but it's a start.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>HTML</mark> making it the first step of many to mastering the language. I have learned many skills through this and been I'm very proud of having this in my portfolio.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in <mark>Cyber Securtiy</mark>, <mark>Software Engineering</mark>, and <mark>System Support</mark> some of my other interests and hobbies are:
      - Video game development
      - Video editing
      - Streaming
      - Creating enthusiast computer builds
      - Tinkering with my homelab

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
