# Content configuration version
version: 2

# Personal info
name: Bradley Kars
title: System Support Specialist
email: bradley.kars@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: 
github_username:  slayerbrk
# stackoverflow_username: 
linkedin_username: bradley-kars
# youtube_username: 

# Additional icon links
additional_links:
#- title: 
#  icon: 
#  url: 
# - title: 
#   icon: 
#   url: 

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Bradley and I’ve done everything from helping to build a budding national organization run by students in the hopes of furthering their education; to running the IT department of a commercial construction company. I’ve now returned to furthering my education where I’m a Dean’s list student at Purdue University Global. Where I’m toward my Bachelor of Science in Cybersecurity with a focus in Game Development, while simultaneously employed as a System Support Specialist Intern.

  I am most skilled in: <mark>System Support</mark> and <mark>Hardware Diagnostics</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CentralSquare Technologies
        link: https://www.centralsquare.com/
        link_text: CentralSquare
        sub_title: System Support Specialist Intern
        caption: March 2022 - Present
        quote: >
          Creating the broadest, smartest and most agile software platform for building safer, smarter communities.
        description: | # this will include new lines to allow paragraphs
            Every company needs its systems properly supported and CentralSquare is no exception. Devloping, deploying, and maintianing software is hard and I play my part making sure the whole company stays connected. I work hand and hand with people from every department to keep their systems functioning as they need.
      - layout: left
        title: Kars Customs
        link: 
        link_text: 
        sub_title: Owner/Lead Repair Tech
        caption: September 2016 - Present
        quote: >
          Aiming to make your life easier by providing support and a knowledge base for your technological needs.
        description: | # this will include new lines to allow paragraphs
            Here to help every step of the way from guiding customers through purchases, to finding them the best deals while supporting their devices for as long as they want to keep them. All under the goal of making it so technology can do its job and truly make their lives easier.
      - layout: left
        title: MarketSource Inc.
        link: https://www.marketsource.com/
        link_text: MarketSource
        sub_title: Team Lead
        caption: July 2018 - March 2020
        quote: >
          Technologists committed to making Target America's easiest, safest, and most joyful place to shop and work.
        description: | # this will include new lines to allow paragraphs
            There to help target customers make informed purchases regarding cellular devices while also offering help maintaining said devices. Our goal is to make sure the customer gets what they need from their devices on plans that just work. This includes but is not limited to helping customers choose their devices, diagnosing and fixing basic device issues, and even communicating with their individual carriers on their behalf.
      - layout: left
        title: ESCO Services LLC
        link: 
        link_text: 
        sub_title: Estimating Engineer - IT Specialist
        caption: January 2012 - May 2015
        quote: >
          Leaders in quality construction and innovation.
        description: | # this will include new lines to allow paragraphs
            Every company needs IT from multimillion dollar organizations to small ma and pa shops and the construction industry is no different. While the systems involved may be less complex devices still need to be maintained, computers kept running, and software configured.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Purdue University Global
        caption: March 2022 - Present
        sub_title: Bachelor of Science in Cybersecurity - Game Development
        quote: >
          With a history of pioneering online education, Purdue Global’s mission is simple: deliver a fully personalized online learning experience that's tailored to the unique needs of working adults—one that gives you the support you need to achieve your goals and creates new opportunities for your future. While maintaining its image as part of the Renowned Purdue University System.
        description: | # this will include new lines to allow paragraphs
          During my time at Purdue Global I maintained a 3.98 GPA keeping my place on the Dean's list while learning how to better protect the systems I support.
      - layout: left
        caption: October 2020 – January 2022
        sub_title: Associate of Applied Science in Information Technology - IT Generalist
        description: | # this will include new lines to allow paragraphs
          During my time at Purdue Global I maintained a 4.00 GPA keeping my place on the Chancellor’s list while obtaining the necessary tools to support an IT infrastructure.

  - title: Coding Classes # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: IT117 - Website Development
        link: https://github.com/slayerbrk/slayerbrk.github.io/tree/main/IT117%20-%20Website%20Development
        link_text: Website Development
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The first website I ever created, it may not be perfect but it's a start.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>HTML</mark> making it the first step of many to mastering the laungage. I have learned many skills through this and been I'm very proud of having this in my portfolio.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
